apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-example
  labels:
    app: cloud-native-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-native-example
  template:
    metadata:
      labels:
        app: cloud-native-example
    spec:
      containers:
        - name: cloud-native-example
          image: cjrutherford/cloud-native-example:4764c81
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7880
          env:
            - name: KAFKA_TOPIC
              value: "orders"
            - name: KAFKA_BROKER_ADDRESS
              value: "kafka-broker.kafka"
            - name: KAFKA_BROKER_PORT
              value: "9092"
